(DEFPACKAGE :WL
  (:USE #:CL)
  (:EXPORT WL-OBJECT *OBJECTS* MATCH-EVENT-OPCODE MATCH-REQUEST-OPCODE))

(IN-PACKAGE :WL)

(DEFVAR *OBJECTS* (MAKE-HASH-TABLE :TEST 'EQ))

(DEFCLASS WL-OBJECT NIL ((ID :INITARG :ID :ACCESSOR ID)))

(DEFGENERIC MATCH-EVENT-OPCODE
    (OBJ OPCODE))

(DEFGENERIC MATCH-REQUEST-OPCODE
    (OBJ OPCODE))

(DEFMETHOD INITIALIZE-INSTANCE :AFTER ((OBJ WL-OBJECT) &KEY)
  (SETF (GETHASH (ID OBJ) WL:*OBJECTS*) OBJ))

(DEFPACKAGE :WL/WL_DISPLAY
  (:USE :CL)
  (:EXPORT REQ-SYNC REQ-GET_REGISTRY EVT-ERROR EVT-DELETE_ID))

(IN-PACKAGE :WL/WL_DISPLAY)

(DEFCLASS WL_DISPLAY (WL:WL-OBJECT)
          ((CLIENT :INITARG :CLIENT :ACCESSOR CLIENT)))

(DEFMETHOD EVT-ERROR ((OBJ WL_DISPLAY) OBJECT_ID CODE MESSAGE)
  (ERROR "Unimplemented"))

(DEFMETHOD EVT-DELETE_ID ((OBJ WL_DISPLAY) ID) (ERROR "Unimplemented"))

(DEFMETHOD REQ-SYNC ((OBJ WL_DISPLAY) CALLBACK) (ERROR "Unimplemented"))

(DEFMETHOD REQ-GET_REGISTRY ((OBJ WL_DISPLAY) REGISTRY) (ERROR "Unimplemented"))

(DEFMETHOD MATCH-EVENT-OPCODE ((OBJ WL_DISPLAY) OPCODE)
  (NTH OPCODE '(EVT-ERROR EVT-DELETE_ID)))

(DEFMETHOD MATCH-REQUEST-OPCODE ((OBJ WL_DISPLAY) OPCODE)
  (NTH OPCODE '(EVT-SYNC EVT-GET_REGISTRY)))

(DEFPACKAGE :WL/WL_REGISTRY
  (:USE :CL)
  (:EXPORT REQ-BIND EVT-GLOBAL EVT-GLOBAL_REMOVE))

(IN-PACKAGE :WL/WL_REGISTRY)

(DEFCLASS WL_REGISTRY (WL:WL-OBJECT)
          ((CLIENT :INITARG :CLIENT :ACCESSOR CLIENT)))

(DEFMETHOD EVT-GLOBAL ((OBJ WL_REGISTRY) NAME INTERFACE VERSION)
  (ERROR "Unimplemented"))

(DEFMETHOD EVT-GLOBAL_REMOVE ((OBJ WL_REGISTRY) NAME) (ERROR "Unimplemented"))

(DEFMETHOD REQ-BIND ((OBJ WL_REGISTRY) NAME ID) (ERROR "Unimplemented"))

(DEFMETHOD MATCH-EVENT-OPCODE ((OBJ WL_REGISTRY) OPCODE)
  (NTH OPCODE '(EVT-GLOBAL EVT-GLOBAL_REMOVE)))

(DEFMETHOD MATCH-REQUEST-OPCODE ((OBJ WL_REGISTRY) OPCODE)
  (NTH OPCODE '(EVT-BIND)))

(DEFPACKAGE :WL/WL_CALLBACK
  (:USE :CL)
  (:EXPORT EVT-DONE))

(IN-PACKAGE :WL/WL_CALLBACK)

(DEFCLASS WL_CALLBACK (WL:WL-OBJECT)
          ((CLIENT :INITARG :CLIENT :ACCESSOR CLIENT)))

(DEFMETHOD EVT-DONE ((OBJ WL_CALLBACK) CALLBACK_DATA) (ERROR "Unimplemented"))

(DEFMETHOD MATCH-EVENT-OPCODE ((OBJ WL_CALLBACK) OPCODE)
  (NTH OPCODE '(EVT-DONE)))

(DEFMETHOD MATCH-REQUEST-OPCODE ((OBJ WL_CALLBACK) OPCODE) (NTH OPCODE 'NIL))

(DEFPACKAGE :WL/WL_COMPOSITOR
  (:USE :CL)
  (:EXPORT REQ-CREATE_SURFACE REQ-CREATE_REGION))

(IN-PACKAGE :WL/WL_COMPOSITOR)

(DEFCLASS WL_COMPOSITOR (WL:WL-OBJECT)
          ((CLIENT :INITARG :CLIENT :ACCESSOR CLIENT)))

(DEFMETHOD REQ-CREATE_SURFACE ((OBJ WL_COMPOSITOR) ID) (ERROR "Unimplemented"))

(DEFMETHOD REQ-CREATE_REGION ((OBJ WL_COMPOSITOR) ID) (ERROR "Unimplemented"))

(DEFMETHOD MATCH-EVENT-OPCODE ((OBJ WL_COMPOSITOR) OPCODE) (NTH OPCODE 'NIL))

(DEFMETHOD MATCH-REQUEST-OPCODE ((OBJ WL_COMPOSITOR) OPCODE)
  (NTH OPCODE '(EVT-CREATE_SURFACE EVT-CREATE_REGION)))

(DEFPACKAGE :WL/WL_SHM_POOL
  (:USE :CL)
  (:EXPORT REQ-CREATE_BUFFER REQ-DESTROY REQ-RESIZE))

(IN-PACKAGE :WL/WL_SHM_POOL)

(DEFCLASS WL_SHM_POOL (WL:WL-OBJECT)
          ((CLIENT :INITARG :CLIENT :ACCESSOR CLIENT)))

(DEFMETHOD REQ-CREATE_BUFFER
           ((OBJ WL_SHM_POOL) ID OFFSET WIDTH HEIGHT STRIDE FORMAT)
  (ERROR "Unimplemented"))

(DEFMETHOD REQ-DESTROY ((OBJ WL_SHM_POOL)) (ERROR "Unimplemented"))

(DEFMETHOD REQ-RESIZE ((OBJ WL_SHM_POOL) SIZE) (ERROR "Unimplemented"))

(DEFMETHOD MATCH-EVENT-OPCODE ((OBJ WL_SHM_POOL) OPCODE) (NTH OPCODE 'NIL))

(DEFMETHOD MATCH-REQUEST-OPCODE ((OBJ WL_SHM_POOL) OPCODE)
  (NTH OPCODE '(EVT-CREATE_BUFFER EVT-DESTROY EVT-RESIZE)))

(DEFPACKAGE :WL/WL_SHM
  (:USE :CL)
  (:EXPORT REQ-CREATE_POOL EVT-FORMAT))

(IN-PACKAGE :WL/WL_SHM)

(DEFCLASS WL_SHM (WL:WL-OBJECT) ((CLIENT :INITARG :CLIENT :ACCESSOR CLIENT)))

(DEFMETHOD EVT-FORMAT ((OBJ WL_SHM) FORMAT) (ERROR "Unimplemented"))

(DEFMETHOD REQ-CREATE_POOL ((OBJ WL_SHM) ID FD SIZE) (ERROR "Unimplemented"))

(DEFMETHOD MATCH-EVENT-OPCODE ((OBJ WL_SHM) OPCODE) (NTH OPCODE '(EVT-FORMAT)))

(DEFMETHOD MATCH-REQUEST-OPCODE ((OBJ WL_SHM) OPCODE)
  (NTH OPCODE '(EVT-CREATE_POOL)))

(DEFPACKAGE :WL/WL_BUFFER
  (:USE :CL)
  (:EXPORT REQ-DESTROY EVT-RELEASE))

(IN-PACKAGE :WL/WL_BUFFER)

(DEFCLASS WL_BUFFER (WL:WL-OBJECT) ((CLIENT :INITARG :CLIENT :ACCESSOR CLIENT)))

(DEFMETHOD EVT-RELEASE ((OBJ WL_BUFFER)) (ERROR "Unimplemented"))

(DEFMETHOD REQ-DESTROY ((OBJ WL_BUFFER)) (ERROR "Unimplemented"))

(DEFMETHOD MATCH-EVENT-OPCODE ((OBJ WL_BUFFER) OPCODE)
  (NTH OPCODE '(EVT-RELEASE)))

(DEFMETHOD MATCH-REQUEST-OPCODE ((OBJ WL_BUFFER) OPCODE)
  (NTH OPCODE '(EVT-DESTROY)))

(DEFPACKAGE :WL/WL_DATA_OFFER
  (:USE :CL)
  (:EXPORT REQ-ACCEPT
           REQ-RECEIVE
           REQ-DESTROY
           REQ-FINISH
           REQ-SET_ACTIONS
           EVT-OFFER
           EVT-SOURCE_ACTIONS
           EVT-ACTION))

(IN-PACKAGE :WL/WL_DATA_OFFER)

(DEFCLASS WL_DATA_OFFER (WL:WL-OBJECT)
          ((CLIENT :INITARG :CLIENT :ACCESSOR CLIENT)))

(DEFMETHOD EVT-OFFER ((OBJ WL_DATA_OFFER) MIME_TYPE) (ERROR "Unimplemented"))

(DEFMETHOD EVT-SOURCE_ACTIONS ((OBJ WL_DATA_OFFER) SOURCE_ACTIONS)
  (ERROR "Unimplemented"))

(DEFMETHOD EVT-ACTION ((OBJ WL_DATA_OFFER) DND_ACTION) (ERROR "Unimplemented"))

(DEFMETHOD REQ-ACCEPT ((OBJ WL_DATA_OFFER) SERIAL MIME_TYPE)
  (ERROR "Unimplemented"))

(DEFMETHOD REQ-RECEIVE ((OBJ WL_DATA_OFFER) MIME_TYPE FD)
  (ERROR "Unimplemented"))

(DEFMETHOD REQ-DESTROY ((OBJ WL_DATA_OFFER)) (ERROR "Unimplemented"))

(DEFMETHOD REQ-FINISH ((OBJ WL_DATA_OFFER)) (ERROR "Unimplemented"))

(DEFMETHOD REQ-SET_ACTIONS ((OBJ WL_DATA_OFFER) DND_ACTIONS PREFERRED_ACTION)
  (ERROR "Unimplemented"))

(DEFMETHOD MATCH-EVENT-OPCODE ((OBJ WL_DATA_OFFER) OPCODE)
  (NTH OPCODE '(EVT-OFFER EVT-SOURCE_ACTIONS EVT-ACTION)))

(DEFMETHOD MATCH-REQUEST-OPCODE ((OBJ WL_DATA_OFFER) OPCODE)
  (NTH OPCODE '(EVT-ACCEPT EVT-RECEIVE EVT-DESTROY EVT-FINISH EVT-SET_ACTIONS)))

(DEFPACKAGE :WL/WL_DATA_SOURCE
  (:USE :CL)
  (:EXPORT REQ-OFFER
           REQ-DESTROY
           REQ-SET_ACTIONS
           EVT-TARGET
           EVT-SEND
           EVT-CANCELLED
           EVT-DND_DROP_PERFORMED
           EVT-DND_FINISHED
           EVT-ACTION))

(IN-PACKAGE :WL/WL_DATA_SOURCE)

(DEFCLASS WL_DATA_SOURCE (WL:WL-OBJECT)
          ((CLIENT :INITARG :CLIENT :ACCESSOR CLIENT)))

(DEFMETHOD EVT-TARGET ((OBJ WL_DATA_SOURCE) MIME_TYPE) (ERROR "Unimplemented"))

(DEFMETHOD EVT-SEND ((OBJ WL_DATA_SOURCE) MIME_TYPE FD) (ERROR "Unimplemented"))

(DEFMETHOD EVT-CANCELLED ((OBJ WL_DATA_SOURCE)) (ERROR "Unimplemented"))

(DEFMETHOD EVT-DND_DROP_PERFORMED ((OBJ WL_DATA_SOURCE))
  (ERROR "Unimplemented"))

(DEFMETHOD EVT-DND_FINISHED ((OBJ WL_DATA_SOURCE)) (ERROR "Unimplemented"))

(DEFMETHOD EVT-ACTION ((OBJ WL_DATA_SOURCE) DND_ACTION) (ERROR "Unimplemented"))

(DEFMETHOD REQ-OFFER ((OBJ WL_DATA_SOURCE) MIME_TYPE) (ERROR "Unimplemented"))

(DEFMETHOD REQ-DESTROY ((OBJ WL_DATA_SOURCE)) (ERROR "Unimplemented"))

(DEFMETHOD REQ-SET_ACTIONS ((OBJ WL_DATA_SOURCE) DND_ACTIONS)
  (ERROR "Unimplemented"))

(DEFMETHOD MATCH-EVENT-OPCODE ((OBJ WL_DATA_SOURCE) OPCODE)
  (NTH OPCODE
       '(EVT-TARGET EVT-SEND EVT-CANCELLED EVT-DND_DROP_PERFORMED
         EVT-DND_FINISHED EVT-ACTION)))

(DEFMETHOD MATCH-REQUEST-OPCODE ((OBJ WL_DATA_SOURCE) OPCODE)
  (NTH OPCODE '(EVT-OFFER EVT-DESTROY EVT-SET_ACTIONS)))

(DEFPACKAGE :WL/WL_DATA_DEVICE
  (:USE :CL)
  (:EXPORT REQ-START_DRAG
           REQ-SET_SELECTION
           REQ-RELEASE
           EVT-DATA_OFFER
           EVT-ENTER
           EVT-LEAVE
           EVT-MOTION
           EVT-DROP
           EVT-SELECTION))

(IN-PACKAGE :WL/WL_DATA_DEVICE)

(DEFCLASS WL_DATA_DEVICE (WL:WL-OBJECT)
          ((CLIENT :INITARG :CLIENT :ACCESSOR CLIENT)))

(DEFMETHOD EVT-DATA_OFFER ((OBJ WL_DATA_DEVICE) ID) (ERROR "Unimplemented"))

(DEFMETHOD EVT-ENTER ((OBJ WL_DATA_DEVICE) SERIAL SURFACE X Y ID)
  (ERROR "Unimplemented"))

(DEFMETHOD EVT-LEAVE ((OBJ WL_DATA_DEVICE)) (ERROR "Unimplemented"))

(DEFMETHOD EVT-MOTION ((OBJ WL_DATA_DEVICE) TIME X Y) (ERROR "Unimplemented"))

(DEFMETHOD EVT-DROP ((OBJ WL_DATA_DEVICE)) (ERROR "Unimplemented"))

(DEFMETHOD EVT-SELECTION ((OBJ WL_DATA_DEVICE) ID) (ERROR "Unimplemented"))

(DEFMETHOD REQ-START_DRAG ((OBJ WL_DATA_DEVICE) SOURCE ORIGIN ICON SERIAL)
  (ERROR "Unimplemented"))

(DEFMETHOD REQ-SET_SELECTION ((OBJ WL_DATA_DEVICE) SOURCE SERIAL)
  (ERROR "Unimplemented"))

(DEFMETHOD REQ-RELEASE ((OBJ WL_DATA_DEVICE)) (ERROR "Unimplemented"))

(DEFMETHOD MATCH-EVENT-OPCODE ((OBJ WL_DATA_DEVICE) OPCODE)
  (NTH OPCODE
       '(EVT-DATA_OFFER EVT-ENTER EVT-LEAVE EVT-MOTION EVT-DROP EVT-SELECTION)))

(DEFMETHOD MATCH-REQUEST-OPCODE ((OBJ WL_DATA_DEVICE) OPCODE)
  (NTH OPCODE '(EVT-START_DRAG EVT-SET_SELECTION EVT-RELEASE)))

(DEFPACKAGE :WL/WL_DATA_DEVICE_MANAGER
  (:USE :CL)
  (:EXPORT REQ-CREATE_DATA_SOURCE REQ-GET_DATA_DEVICE))

(IN-PACKAGE :WL/WL_DATA_DEVICE_MANAGER)

(DEFCLASS WL_DATA_DEVICE_MANAGER (WL:WL-OBJECT)
          ((CLIENT :INITARG :CLIENT :ACCESSOR CLIENT)))

(DEFMETHOD REQ-CREATE_DATA_SOURCE ((OBJ WL_DATA_DEVICE_MANAGER) ID)
  (ERROR "Unimplemented"))

(DEFMETHOD REQ-GET_DATA_DEVICE ((OBJ WL_DATA_DEVICE_MANAGER) ID SEAT)
  (ERROR "Unimplemented"))

(DEFMETHOD MATCH-EVENT-OPCODE ((OBJ WL_DATA_DEVICE_MANAGER) OPCODE)
  (NTH OPCODE 'NIL))

(DEFMETHOD MATCH-REQUEST-OPCODE ((OBJ WL_DATA_DEVICE_MANAGER) OPCODE)
  (NTH OPCODE '(EVT-CREATE_DATA_SOURCE EVT-GET_DATA_DEVICE)))

(DEFPACKAGE :WL/WL_SHELL
  (:USE :CL)
  (:EXPORT REQ-GET_SHELL_SURFACE))

(IN-PACKAGE :WL/WL_SHELL)

(DEFCLASS WL_SHELL (WL:WL-OBJECT) ((CLIENT :INITARG :CLIENT :ACCESSOR CLIENT)))

(DEFMETHOD REQ-GET_SHELL_SURFACE ((OBJ WL_SHELL) ID SURFACE)
  (ERROR "Unimplemented"))

(DEFMETHOD MATCH-EVENT-OPCODE ((OBJ WL_SHELL) OPCODE) (NTH OPCODE 'NIL))

(DEFMETHOD MATCH-REQUEST-OPCODE ((OBJ WL_SHELL) OPCODE)
  (NTH OPCODE '(EVT-GET_SHELL_SURFACE)))

(DEFPACKAGE :WL/WL_SHELL_SURFACE
  (:USE :CL)
  (:EXPORT REQ-PONG
           REQ-MOVE
           REQ-RESIZE
           REQ-SET_TOPLEVEL
           REQ-SET_TRANSIENT
           REQ-SET_FULLSCREEN
           REQ-SET_POPUP
           REQ-SET_MAXIMIZED
           REQ-SET_TITLE
           REQ-SET_CLASS
           EVT-PING
           EVT-CONFIGURE
           EVT-POPUP_DONE))

(IN-PACKAGE :WL/WL_SHELL_SURFACE)

(DEFCLASS WL_SHELL_SURFACE (WL:WL-OBJECT)
          ((CLIENT :INITARG :CLIENT :ACCESSOR CLIENT)))

(DEFMETHOD EVT-PING ((OBJ WL_SHELL_SURFACE) SERIAL) (ERROR "Unimplemented"))

(DEFMETHOD EVT-CONFIGURE ((OBJ WL_SHELL_SURFACE) EDGES WIDTH HEIGHT)
  (ERROR "Unimplemented"))

(DEFMETHOD EVT-POPUP_DONE ((OBJ WL_SHELL_SURFACE)) (ERROR "Unimplemented"))

(DEFMETHOD REQ-PONG ((OBJ WL_SHELL_SURFACE) SERIAL) (ERROR "Unimplemented"))

(DEFMETHOD REQ-MOVE ((OBJ WL_SHELL_SURFACE) SEAT SERIAL)
  (ERROR "Unimplemented"))

(DEFMETHOD REQ-RESIZE ((OBJ WL_SHELL_SURFACE) SEAT SERIAL EDGES)
  (ERROR "Unimplemented"))

(DEFMETHOD REQ-SET_TOPLEVEL ((OBJ WL_SHELL_SURFACE)) (ERROR "Unimplemented"))

(DEFMETHOD REQ-SET_TRANSIENT ((OBJ WL_SHELL_SURFACE) PARENT X Y FLAGS)
  (ERROR "Unimplemented"))

(DEFMETHOD REQ-SET_FULLSCREEN ((OBJ WL_SHELL_SURFACE) METHOD FRAMERATE OUTPUT)
  (ERROR "Unimplemented"))

(DEFMETHOD REQ-SET_POPUP ((OBJ WL_SHELL_SURFACE) SEAT SERIAL PARENT X Y FLAGS)
  (ERROR "Unimplemented"))

(DEFMETHOD REQ-SET_MAXIMIZED ((OBJ WL_SHELL_SURFACE) OUTPUT)
  (ERROR "Unimplemented"))

(DEFMETHOD REQ-SET_TITLE ((OBJ WL_SHELL_SURFACE) TITLE) (ERROR "Unimplemented"))

(DEFMETHOD REQ-SET_CLASS ((OBJ WL_SHELL_SURFACE) CLASS_)
  (ERROR "Unimplemented"))

(DEFMETHOD MATCH-EVENT-OPCODE ((OBJ WL_SHELL_SURFACE) OPCODE)
  (NTH OPCODE '(EVT-PING EVT-CONFIGURE EVT-POPUP_DONE)))

(DEFMETHOD MATCH-REQUEST-OPCODE ((OBJ WL_SHELL_SURFACE) OPCODE)
  (NTH OPCODE
       '(EVT-PONG EVT-MOVE EVT-RESIZE EVT-SET_TOPLEVEL EVT-SET_TRANSIENT
         EVT-SET_FULLSCREEN EVT-SET_POPUP EVT-SET_MAXIMIZED EVT-SET_TITLE
         EVT-SET_CLASS)))

(DEFPACKAGE :WL/WL_SURFACE
  (:USE :CL)
  (:EXPORT REQ-DESTROY
           REQ-ATTACH
           REQ-DAMAGE
           REQ-FRAME
           REQ-SET_OPAQUE_REGION
           REQ-SET_INPUT_REGION
           REQ-COMMIT
           REQ-SET_BUFFER_TRANSFORM
           REQ-SET_BUFFER_SCALE
           REQ-DAMAGE_BUFFER
           REQ-OFFSET
           EVT-ENTER
           EVT-LEAVE
           EVT-PREFERRED_BUFFER_SCALE
           EVT-PREFERRED_BUFFER_TRANSFORM))

(IN-PACKAGE :WL/WL_SURFACE)

(DEFCLASS WL_SURFACE (WL:WL-OBJECT)
          ((CLIENT :INITARG :CLIENT :ACCESSOR CLIENT)))

(DEFMETHOD EVT-ENTER ((OBJ WL_SURFACE) OUTPUT) (ERROR "Unimplemented"))

(DEFMETHOD EVT-LEAVE ((OBJ WL_SURFACE) OUTPUT) (ERROR "Unimplemented"))

(DEFMETHOD EVT-PREFERRED_BUFFER_SCALE ((OBJ WL_SURFACE) FACTOR)
  (ERROR "Unimplemented"))

(DEFMETHOD EVT-PREFERRED_BUFFER_TRANSFORM ((OBJ WL_SURFACE) TRANSFORM)
  (ERROR "Unimplemented"))

(DEFMETHOD REQ-DESTROY ((OBJ WL_SURFACE)) (ERROR "Unimplemented"))

(DEFMETHOD REQ-ATTACH ((OBJ WL_SURFACE) BUFFER X Y) (ERROR "Unimplemented"))

(DEFMETHOD REQ-DAMAGE ((OBJ WL_SURFACE) X Y WIDTH HEIGHT)
  (ERROR "Unimplemented"))

(DEFMETHOD REQ-FRAME ((OBJ WL_SURFACE) CALLBACK) (ERROR "Unimplemented"))

(DEFMETHOD REQ-SET_OPAQUE_REGION ((OBJ WL_SURFACE) REGION)
  (ERROR "Unimplemented"))

(DEFMETHOD REQ-SET_INPUT_REGION ((OBJ WL_SURFACE) REGION)
  (ERROR "Unimplemented"))

(DEFMETHOD REQ-COMMIT ((OBJ WL_SURFACE)) (ERROR "Unimplemented"))

(DEFMETHOD REQ-SET_BUFFER_TRANSFORM ((OBJ WL_SURFACE) TRANSFORM)
  (ERROR "Unimplemented"))

(DEFMETHOD REQ-SET_BUFFER_SCALE ((OBJ WL_SURFACE) SCALE)
  (ERROR "Unimplemented"))

(DEFMETHOD REQ-DAMAGE_BUFFER ((OBJ WL_SURFACE) X Y WIDTH HEIGHT)
  (ERROR "Unimplemented"))

(DEFMETHOD REQ-OFFSET ((OBJ WL_SURFACE) X Y) (ERROR "Unimplemented"))

(DEFMETHOD MATCH-EVENT-OPCODE ((OBJ WL_SURFACE) OPCODE)
  (NTH OPCODE
       '(EVT-ENTER EVT-LEAVE EVT-PREFERRED_BUFFER_SCALE
         EVT-PREFERRED_BUFFER_TRANSFORM)))

(DEFMETHOD MATCH-REQUEST-OPCODE ((OBJ WL_SURFACE) OPCODE)
  (NTH OPCODE
       '(EVT-DESTROY EVT-ATTACH EVT-DAMAGE EVT-FRAME EVT-SET_OPAQUE_REGION
         EVT-SET_INPUT_REGION EVT-COMMIT EVT-SET_BUFFER_TRANSFORM
         EVT-SET_BUFFER_SCALE EVT-DAMAGE_BUFFER EVT-OFFSET)))

(DEFPACKAGE :WL/WL_SEAT
  (:USE :CL)
  (:EXPORT REQ-GET_POINTER
           REQ-GET_KEYBOARD
           REQ-GET_TOUCH
           REQ-RELEASE
           EVT-CAPABILITIES
           EVT-NAME))

(IN-PACKAGE :WL/WL_SEAT)

(DEFCLASS WL_SEAT (WL:WL-OBJECT) ((CLIENT :INITARG :CLIENT :ACCESSOR CLIENT)))

(DEFMETHOD EVT-CAPABILITIES ((OBJ WL_SEAT) CAPABILITIES)
  (ERROR "Unimplemented"))

(DEFMETHOD EVT-NAME ((OBJ WL_SEAT) NAME) (ERROR "Unimplemented"))

(DEFMETHOD REQ-GET_POINTER ((OBJ WL_SEAT) ID) (ERROR "Unimplemented"))

(DEFMETHOD REQ-GET_KEYBOARD ((OBJ WL_SEAT) ID) (ERROR "Unimplemented"))

(DEFMETHOD REQ-GET_TOUCH ((OBJ WL_SEAT) ID) (ERROR "Unimplemented"))

(DEFMETHOD REQ-RELEASE ((OBJ WL_SEAT)) (ERROR "Unimplemented"))

(DEFMETHOD MATCH-EVENT-OPCODE ((OBJ WL_SEAT) OPCODE)
  (NTH OPCODE '(EVT-CAPABILITIES EVT-NAME)))

(DEFMETHOD MATCH-REQUEST-OPCODE ((OBJ WL_SEAT) OPCODE)
  (NTH OPCODE '(EVT-GET_POINTER EVT-GET_KEYBOARD EVT-GET_TOUCH EVT-RELEASE)))

(DEFPACKAGE :WL/WL_POINTER
  (:USE :CL)
  (:EXPORT REQ-SET_CURSOR
           REQ-RELEASE
           EVT-ENTER
           EVT-LEAVE
           EVT-MOTION
           EVT-BUTTON
           EVT-AXIS
           EVT-FRAME
           EVT-AXIS_SOURCE
           EVT-AXIS_STOP
           EVT-AXIS_DISCRETE
           EVT-AXIS_VALUE120
           EVT-AXIS_RELATIVE_DIRECTION))

(IN-PACKAGE :WL/WL_POINTER)

(DEFCLASS WL_POINTER (WL:WL-OBJECT)
          ((CLIENT :INITARG :CLIENT :ACCESSOR CLIENT)))

(DEFMETHOD EVT-ENTER ((OBJ WL_POINTER) SERIAL SURFACE SURFACE_X SURFACE_Y)
  (ERROR "Unimplemented"))

(DEFMETHOD EVT-LEAVE ((OBJ WL_POINTER) SERIAL SURFACE) (ERROR "Unimplemented"))

(DEFMETHOD EVT-MOTION ((OBJ WL_POINTER) TIME SURFACE_X SURFACE_Y)
  (ERROR "Unimplemented"))

(DEFMETHOD EVT-BUTTON ((OBJ WL_POINTER) SERIAL TIME BUTTON STATE)
  (ERROR "Unimplemented"))

(DEFMETHOD EVT-AXIS ((OBJ WL_POINTER) TIME AXIS VALUE) (ERROR "Unimplemented"))

(DEFMETHOD EVT-FRAME ((OBJ WL_POINTER)) (ERROR "Unimplemented"))

(DEFMETHOD EVT-AXIS_SOURCE ((OBJ WL_POINTER) AXIS_SOURCE)
  (ERROR "Unimplemented"))

(DEFMETHOD EVT-AXIS_STOP ((OBJ WL_POINTER) TIME AXIS) (ERROR "Unimplemented"))

(DEFMETHOD EVT-AXIS_DISCRETE ((OBJ WL_POINTER) AXIS DISCRETE)
  (ERROR "Unimplemented"))

(DEFMETHOD EVT-AXIS_VALUE120 ((OBJ WL_POINTER) AXIS VALUE120)
  (ERROR "Unimplemented"))

(DEFMETHOD EVT-AXIS_RELATIVE_DIRECTION ((OBJ WL_POINTER) AXIS DIRECTION)
  (ERROR "Unimplemented"))

(DEFMETHOD REQ-SET_CURSOR ((OBJ WL_POINTER) SERIAL SURFACE HOTSPOT_X HOTSPOT_Y)
  (ERROR "Unimplemented"))

(DEFMETHOD REQ-RELEASE ((OBJ WL_POINTER)) (ERROR "Unimplemented"))

(DEFMETHOD MATCH-EVENT-OPCODE ((OBJ WL_POINTER) OPCODE)
  (NTH OPCODE
       '(EVT-ENTER EVT-LEAVE EVT-MOTION EVT-BUTTON EVT-AXIS EVT-FRAME
         EVT-AXIS_SOURCE EVT-AXIS_STOP EVT-AXIS_DISCRETE EVT-AXIS_VALUE120
         EVT-AXIS_RELATIVE_DIRECTION)))

(DEFMETHOD MATCH-REQUEST-OPCODE ((OBJ WL_POINTER) OPCODE)
  (NTH OPCODE '(EVT-SET_CURSOR EVT-RELEASE)))

(DEFPACKAGE :WL/WL_KEYBOARD
  (:USE :CL)
  (:EXPORT REQ-RELEASE
           EVT-KEYMAP
           EVT-ENTER
           EVT-LEAVE
           EVT-KEY
           EVT-MODIFIERS
           EVT-REPEAT_INFO))

(IN-PACKAGE :WL/WL_KEYBOARD)

(DEFCLASS WL_KEYBOARD (WL:WL-OBJECT)
          ((CLIENT :INITARG :CLIENT :ACCESSOR CLIENT)))

(DEFMETHOD EVT-KEYMAP ((OBJ WL_KEYBOARD) FORMAT FD SIZE)
  (ERROR "Unimplemented"))

(DEFMETHOD EVT-ENTER ((OBJ WL_KEYBOARD) SERIAL SURFACE KEYS)
  (ERROR "Unimplemented"))

(DEFMETHOD EVT-LEAVE ((OBJ WL_KEYBOARD) SERIAL SURFACE) (ERROR "Unimplemented"))

(DEFMETHOD EVT-KEY ((OBJ WL_KEYBOARD) SERIAL TIME KEY STATE)
  (ERROR "Unimplemented"))

(DEFMETHOD EVT-MODIFIERS
           ((OBJ WL_KEYBOARD) SERIAL MODS_DEPRESSED MODS_LATCHED MODS_LOCKED
            GROUP)
  (ERROR "Unimplemented"))

(DEFMETHOD EVT-REPEAT_INFO ((OBJ WL_KEYBOARD) RATE DELAY)
  (ERROR "Unimplemented"))

(DEFMETHOD REQ-RELEASE ((OBJ WL_KEYBOARD)) (ERROR "Unimplemented"))

(DEFMETHOD MATCH-EVENT-OPCODE ((OBJ WL_KEYBOARD) OPCODE)
  (NTH OPCODE
       '(EVT-KEYMAP EVT-ENTER EVT-LEAVE EVT-KEY EVT-MODIFIERS EVT-REPEAT_INFO)))

(DEFMETHOD MATCH-REQUEST-OPCODE ((OBJ WL_KEYBOARD) OPCODE)
  (NTH OPCODE '(EVT-RELEASE)))

(DEFPACKAGE :WL/WL_TOUCH
  (:USE :CL)
  (:EXPORT REQ-RELEASE
           EVT-DOWN
           EVT-UP
           EVT-MOTION
           EVT-FRAME
           EVT-CANCEL
           EVT-SHAPE
           EVT-ORIENTATION))

(IN-PACKAGE :WL/WL_TOUCH)

(DEFCLASS WL_TOUCH (WL:WL-OBJECT) ((CLIENT :INITARG :CLIENT :ACCESSOR CLIENT)))

(DEFMETHOD EVT-DOWN ((OBJ WL_TOUCH) SERIAL TIME SURFACE ID X Y)
  (ERROR "Unimplemented"))

(DEFMETHOD EVT-UP ((OBJ WL_TOUCH) SERIAL TIME ID) (ERROR "Unimplemented"))

(DEFMETHOD EVT-MOTION ((OBJ WL_TOUCH) TIME ID X Y) (ERROR "Unimplemented"))

(DEFMETHOD EVT-FRAME ((OBJ WL_TOUCH)) (ERROR "Unimplemented"))

(DEFMETHOD EVT-CANCEL ((OBJ WL_TOUCH)) (ERROR "Unimplemented"))

(DEFMETHOD EVT-SHAPE ((OBJ WL_TOUCH) ID MAJOR MINOR) (ERROR "Unimplemented"))

(DEFMETHOD EVT-ORIENTATION ((OBJ WL_TOUCH) ID ORIENTATION)
  (ERROR "Unimplemented"))

(DEFMETHOD REQ-RELEASE ((OBJ WL_TOUCH)) (ERROR "Unimplemented"))

(DEFMETHOD MATCH-EVENT-OPCODE ((OBJ WL_TOUCH) OPCODE)
  (NTH OPCODE
       '(EVT-DOWN EVT-UP EVT-MOTION EVT-FRAME EVT-CANCEL EVT-SHAPE
         EVT-ORIENTATION)))

(DEFMETHOD MATCH-REQUEST-OPCODE ((OBJ WL_TOUCH) OPCODE)
  (NTH OPCODE '(EVT-RELEASE)))

(DEFPACKAGE :WL/WL_OUTPUT
  (:USE :CL)
  (:EXPORT REQ-RELEASE
           EVT-GEOMETRY
           EVT-MODE
           EVT-DONE
           EVT-SCALE
           EVT-NAME
           EVT-DESCRIPTION))

(IN-PACKAGE :WL/WL_OUTPUT)

(DEFCLASS WL_OUTPUT (WL:WL-OBJECT) ((CLIENT :INITARG :CLIENT :ACCESSOR CLIENT)))

(DEFMETHOD EVT-GEOMETRY
           ((OBJ WL_OUTPUT) X Y PHYSICAL_WIDTH PHYSICAL_HEIGHT SUBPIXEL MAKE
            MODEL TRANSFORM)
  (ERROR "Unimplemented"))

(DEFMETHOD EVT-MODE ((OBJ WL_OUTPUT) FLAGS WIDTH HEIGHT REFRESH)
  (ERROR "Unimplemented"))

(DEFMETHOD EVT-DONE ((OBJ WL_OUTPUT)) (ERROR "Unimplemented"))

(DEFMETHOD EVT-SCALE ((OBJ WL_OUTPUT) FACTOR) (ERROR "Unimplemented"))

(DEFMETHOD EVT-NAME ((OBJ WL_OUTPUT) NAME) (ERROR "Unimplemented"))

(DEFMETHOD EVT-DESCRIPTION ((OBJ WL_OUTPUT) DESCRIPTION)
  (ERROR "Unimplemented"))

(DEFMETHOD REQ-RELEASE ((OBJ WL_OUTPUT)) (ERROR "Unimplemented"))

(DEFMETHOD MATCH-EVENT-OPCODE ((OBJ WL_OUTPUT) OPCODE)
  (NTH OPCODE
       '(EVT-GEOMETRY EVT-MODE EVT-DONE EVT-SCALE EVT-NAME EVT-DESCRIPTION)))

(DEFMETHOD MATCH-REQUEST-OPCODE ((OBJ WL_OUTPUT) OPCODE)
  (NTH OPCODE '(EVT-RELEASE)))

(DEFPACKAGE :WL/WL_REGION
  (:USE :CL)
  (:EXPORT REQ-DESTROY REQ-ADD REQ-SUBTRACT))

(IN-PACKAGE :WL/WL_REGION)

(DEFCLASS WL_REGION (WL:WL-OBJECT) ((CLIENT :INITARG :CLIENT :ACCESSOR CLIENT)))

(DEFMETHOD REQ-DESTROY ((OBJ WL_REGION)) (ERROR "Unimplemented"))

(DEFMETHOD REQ-ADD ((OBJ WL_REGION) X Y WIDTH HEIGHT) (ERROR "Unimplemented"))

(DEFMETHOD REQ-SUBTRACT ((OBJ WL_REGION) X Y WIDTH HEIGHT)
  (ERROR "Unimplemented"))

(DEFMETHOD MATCH-EVENT-OPCODE ((OBJ WL_REGION) OPCODE) (NTH OPCODE 'NIL))

(DEFMETHOD MATCH-REQUEST-OPCODE ((OBJ WL_REGION) OPCODE)
  (NTH OPCODE '(EVT-DESTROY EVT-ADD EVT-SUBTRACT)))

(DEFPACKAGE :WL/WL_SUBCOMPOSITOR
  (:USE :CL)
  (:EXPORT REQ-DESTROY REQ-GET_SUBSURFACE))

(IN-PACKAGE :WL/WL_SUBCOMPOSITOR)

(DEFCLASS WL_SUBCOMPOSITOR (WL:WL-OBJECT)
          ((CLIENT :INITARG :CLIENT :ACCESSOR CLIENT)))

(DEFMETHOD REQ-DESTROY ((OBJ WL_SUBCOMPOSITOR)) (ERROR "Unimplemented"))

(DEFMETHOD REQ-GET_SUBSURFACE ((OBJ WL_SUBCOMPOSITOR) ID SURFACE PARENT)
  (ERROR "Unimplemented"))

(DEFMETHOD MATCH-EVENT-OPCODE ((OBJ WL_SUBCOMPOSITOR) OPCODE) (NTH OPCODE 'NIL))

(DEFMETHOD MATCH-REQUEST-OPCODE ((OBJ WL_SUBCOMPOSITOR) OPCODE)
  (NTH OPCODE '(EVT-DESTROY EVT-GET_SUBSURFACE)))

(DEFPACKAGE :WL/WL_SUBSURFACE
  (:USE :CL)
  (:EXPORT REQ-DESTROY
           REQ-SET_POSITION
           REQ-PLACE_ABOVE
           REQ-PLACE_BELOW
           REQ-SET_SYNC
           REQ-SET_DESYNC))

(IN-PACKAGE :WL/WL_SUBSURFACE)

(DEFCLASS WL_SUBSURFACE (WL:WL-OBJECT)
          ((CLIENT :INITARG :CLIENT :ACCESSOR CLIENT)))

(DEFMETHOD REQ-DESTROY ((OBJ WL_SUBSURFACE)) (ERROR "Unimplemented"))

(DEFMETHOD REQ-SET_POSITION ((OBJ WL_SUBSURFACE) X Y) (ERROR "Unimplemented"))

(DEFMETHOD REQ-PLACE_ABOVE ((OBJ WL_SUBSURFACE) SIBLING)
  (ERROR "Unimplemented"))

(DEFMETHOD REQ-PLACE_BELOW ((OBJ WL_SUBSURFACE) SIBLING)
  (ERROR "Unimplemented"))

(DEFMETHOD REQ-SET_SYNC ((OBJ WL_SUBSURFACE)) (ERROR "Unimplemented"))

(DEFMETHOD REQ-SET_DESYNC ((OBJ WL_SUBSURFACE)) (ERROR "Unimplemented"))

(DEFMETHOD MATCH-EVENT-OPCODE ((OBJ WL_SUBSURFACE) OPCODE) (NTH OPCODE 'NIL))

(DEFMETHOD MATCH-REQUEST-OPCODE ((OBJ WL_SUBSURFACE) OPCODE)
  (NTH OPCODE
       '(EVT-DESTROY EVT-SET_POSITION EVT-PLACE_ABOVE EVT-PLACE_BELOW
         EVT-SET_SYNC EVT-SET_DESYNC)))

