(DEFPACKAGE :WL
  (:USE #:CL)
  (:EXPORT WL-OBJECT
           MATCH-EVENT-OPCODE
           MATCH-REQUEST-OPCODE
           GET-REQUEST-ARG-TYPES
           ID
           IFNAME
           VERSION
           INT
           UINT
           OBJECT
           NEW_ID
           FIXED
           STRING
           ARRAY
           FD
           ENUM))

(IN-PACKAGE :WL)

(DEFVAR *ARG-TYPE-SYMBOLS* '(INT UINT OBJECT NEW_ID FIXED STRING ARRAY FD ENUM))

(DEFCLASS WL-OBJECT NIL
          ((ID :INITARG :ID :ACCESSOR ID)
           (IFNAME :INITARG :IFNAME :READER IFNAME)
           (VERSION :INITARG :VERSION :READER VERSION)))

(DEFGENERIC MATCH-EVENT-OPCODE
    (OBJ OPCODE))

(DEFGENERIC MATCH-REQUEST-OPCODE
    (OBJ OPCODE))

(DEFGENERIC GET-REQUEST-ARG-TYPES
    (OBJ OPCODE))

